version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_job_management
    ports:
      - '5438:5432'
#    volumes:
#      - /postgres-data:/var/lib/postgresql/data
#
#volumes:
#  postgres-data:
#    driver: local
