version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_job_management
    ports:
      - '5438:5432'
    volumes:
      - /postgres-data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:9.9.0-community
    container_name: sonarqube
    restart: always
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/db_job_management
      - SONAR_JDBC_USERNAME=admin
      - SONAR_JDBC_PASSWORD=admin
    depends_on:
      - postgres
    ports:
      - '9000:9000'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - jm-network
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - jm-network
    ports:
      - 3000:3000

networks:
    jm-network:
      driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  postgres-data:

